version: "3.9"

services:
  nodejs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - ${WEBSOCKET_PORT}:${WEBSOCKET_PORT}
    networks:
      - xball-local
    command: nodemon src/Server/WebSocketServer.ts

  aimanager:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - .:/app
    networks:
      - xball-local
    command: nodemon src/Ai/AiManager.ts
    depends_on:
      - nodejs

networks:
  xball-local:
    driver: bridge
